name = "Dishonored"

[identifiers]
# steam_app_id = 205100
heroic_names = ["Dishonored"]

[tools.we_mod]
name = "WeMod / Treinadores"
description = "Dependências comuns para treinadores e mods que injetam DLLs"
winetricks = ["dotnet48", "vcrun2022"]
