name = "HITMAN World of Assassination"

[identifiers]
steam_app_id = 1659040
heroic_names = ["HITMAN 3", "HITMAN World of Assassination"]

[tools.simple_mod_framework]
name = "Simple Mod Framework (SMF)"
description = "Gerenciador de mods principal para Hitman 3"
winetricks = ["dotnetdesktop7", "d3dcompiler_47"]
